repos:
- repo: local
  hooks:
      - id: pytest-check
        name: Run tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.2
  hooks:
    # Run the linter.
    - id: ruff
      name: ruff check (linter)
    # Run the formatter.
    - id: ruff-format
      name: ruff format

- repo: https://github.com/rubik/xenon
  rev: v0.9.0
  hooks:
    # Run the linter.
    - id: xenon
      name: Xenon code complexity checker
      args: [ --max-absolute A, --max-modules A, --max-average A ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    -   id: no-commit-to-branch
        name: Don't commit to main/master